# Generated by Django 2.2.6 on 2019-10-21 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]{1}[0-9]{9}$')])),
                ('instagram', models.CharField(max_length=50)),
                ('three_rappers', models.CharField(max_length=100)),
                ('three_songs', models.CharField(max_length=100)),
                ('three_rap_songs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stage_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[6-9]{1}[0-9]{9}$')])),
                ('instagram', models.CharField(max_length=50)),
            ],
        ),
    ]
